### ISSUE TITLE
The navigation bar on the mobile responsive

### ISSUE THREAD

**Issue by manulthanura** [Tailus-UI/astro-theme#2]
The navigation bar on the mobile screen has an error!
On the mobile responsive view, when we click a link in the list of links and go, but navigation popup is not closing.

01. The mobile responsive looks like this

![Tailwind Awesome - Google Chrome 3_20_2023 8_51_47 AM](https://user-images.githubusercontent.com/91767649/226239472-4073e70d-3d6a-4112-980f-f0d477eff851.png)

02. Open the list of links

![Tailwind Awesome - Google Chrome 3_20_2023 8_51_58 AM](https://user-images.githubusercontent.com/91767649/226239591-2b578bfc-1339-4ff9-aff6-3f7a1d046ac0.png)

03. After clicking one of the links

![Tailwind Awesome - Google Chrome 3_20_2023 8_52_21 AM](https://user-images.githubusercontent.com/91767649/226239661-adff5ee4-41dc-4b67-9cdf-26a14a67a1a0.png)

**Comment by AdhamNasr** [comment]
Same issue here, also one of the pictures in testimonials is visible if you scroll down to it.... I think we could use this as a hint to find the bug that's causing this.
![Screenshot 2023-03-28 at 13-08-14 Alexandrina](https://user-images.githubusercontent.com/89584763/228217937-f3316895-582c-4f85-b3ea-f36e37df6f09.png)
